blank_issues_enabled: false
contact_links:
  - name: ðŸ’¬ General Discussion
    url: https://github.com/GabeDuarteM/blocky-ui/discussions
    about: Ask questions or discuss something with the community
